# Generated by Django 6.0.3 on 2026-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='location_type',
            field=models.CharField(choices=[('upstairs', 'Upstairs'), ('downstairs', 'Downstairs')], default='downstairs', max_length=10),
        ),
    ]
